version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./Codeclash-server
    volumes:
      - /app/node_modules
      - ./Codeclash-server:/app

  client:
    stdin_open: true
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./Codeclash
    volumes:
      - /app/node_modules
      - ./Codeclash:/app

